# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci package.
sudo: required
dist: bionic
services:
  - docker
language: cpp
compiler: gcc
cache: ccache

notifications:
  email:
    recipients:
      - rhaschke@techfak.uni-bielefeld.de
      - me@v4hn.de
env:
  global:
    - ROS_DISTRO=melodic
    - UPSTREAM_WORKSPACE=.rosinstall
  matrix:
    - TEST=clang-format
    - TEST=code-coverage ROS_REPO=ros-shadow-fixed
    - DOCKER_IMAGE=moveit/moveit:master-source

before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  - .moveit_ci/travis.sh
