# By default, the task type is 
byte PICK_ONLY=0
byte PLACE_ONLY=1
byte PICK_AND_PLACE=2
byte task_type

# Planning group properties
string arm_group_name
string hand_group_name

# Robot model and links
string eef_name
string hand_frame

# Object and surfaces
string object_id
string[] support_surfaces

# Picking
string grasp_provider_plugin_name
moveit_msgs/Grasp[] grasps
geometry_msgs/Pose grasp_frame_transform

# Placing
string place_provider_plugin_name
moveit_msgs/PlaceLocation[] place_locations

---

bool success
Solution solution

---

string feedback
